# 循环的使用

## for循环

<br>

```js
const arr = [11,22,33,44,55]
let arr1 = []
const fn = () => {
  for (let i = 0; i < arr.length; i++) {
    if (arr[i] === 33) {
      // return
      break
      // continue
    }
    arr1.push(arr[i])
  }
  console.log('不影响函数执行')
}
fn()
console.log(arr1)
```

### for循环中使用return
    会直接跳出整体循环以及循环的外层函数
### for循环中使用break
    跳出整体循环，不影响循环的外层函数
### for循环中使用continue
    跳出当前循环，不影响循环的外层函数

## forEach

<br>

```js
const arr = [11,22,33,44,55]
let arr1 = []
const fn = () => {
  arr.forEach(item => {
    if (item === 33) {
      // break
      return
    }
    arr1.push(item)
  })
  console.log('不影响函数执行')
}
fn()
console.log(arr1)
```

### forEach中使用return
    跳出当前循环，不影响循环的外层函数
### forEach中使用break
    报错，无法使用
### forEach中使用continue
    报错，无法使用

## for in 和 for in

<br>

```js
const arr = [11,22,33,44,55]
let arr1 = []
const fn = () => {
  for(let i in arr) {
        if (arr[i] === 33) {
          // break
          // return
          continue
        }
        arr1.push(arr[i])
      }
  console.log('不影响函数执行')
}
fn()
console.log(arr1)
```

### for in 和 for of中使用return
    跳出整体循环，影响循环的外层函数
### for in 和 for of中使用break
    跳出整体循环，不影响循环的外层函数
### for in 和 for of中使用continue
    跳出当前循环，不影响循环的外层函数

## 跳出当前循环
    map()和forEach()跳出整体循环，可以使用``try catch``语句
    在需要跳出的地方抛出一个错误``throw Error()``
